# Generated by Django 2.2.6 on 2020-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0109_auto_20191006_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_standard',
            field=models.BooleanField(default=True),
        ),
    ]
