# Generated by Django 2.2.6 on 2020-03-25 13:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import saleor.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0109_auto_20191006_1433'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0034_service_account_token'),
        ('order', '0076_auto_20191018_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('phone', saleor.account.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('can_add_product', models.BooleanField(default=False)),
                ('can_add_order', models.BooleanField(default=False)),
                ('can_see_orders', models.BooleanField(default=True)),
                ('can_fulfill_orders', models.BooleanField(default=False)),
                ('can_see_dashboard', models.BooleanField(default=True)),
                ('can_add_customer', models.BooleanField(default=False)),
                ('can_see_customers', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.Address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_available', models.BooleanField(default=False)),
                ('variant_stock_qty', models.IntegerField(default=Decimal('1'), validators=[django.core.validators.MinValueValidator(0)])),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_product_variants', to='partner.Partner')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_variants', to='product.ProductVariant')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_partner', to='partner.Partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_products', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('can_fulfill', models.BooleanField(default=True)),
                ('can_offer', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_partner', to='order.Order')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_orders', to='partner.Partner')),
            ],
        ),
    ]
