# Generated by Django 2.2.6 on 2020-04-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_django_price_2'),
        ('account', '0034_service_account_token'),
        ('partner', '0003_auto_20200329_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='partner.Partner')),
                ('point_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_points', to='account.Address')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='PartnerCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_collect', models.BooleanField(default=True)),
                ('can_publish', models.BooleanField(default=True)),
                ('order_expiry_days', models.IntegerField(default=7)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext', to='checkout.Checkout')),
            ],
        ),
    ]
