# Generated by Django 2.2.6 on 2020-05-12 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_auto_20200510_0757'),
        ('partner', '0004_partnercheckout_partnerpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFulfillmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.CharField(blank=True, default='', max_length=255)),
                ('line_status', models.CharField(blank=True, default='', max_length=255)),
                ('fulfillment_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_lines', to='order.FulfillmentLine')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerFulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_status', models.CharField(max_length=32)),
                ('amount', models.CharField(max_length=32)),
                ('est_shipping_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fulfillment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='partnerfulfillments', to='order.Fulfillment')),
                ('partner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='partnerfulfillments', to='partner.Partner')),
            ],
        ),
    ]
