# Generated by Django 2.2.2 on 2019-08-17 08:22

from django.db import migrations
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_user_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
    ]
